package utils.formbeans;

import java.sql.Timestamp;

import utils.validator.ValidatorFormAndAction;

/**
 * This class is a formbean which all the formbeans of action extend of. It is a formBean which includes all the informacion. By default it includes an autogenerated id, and empty/null values.
 * @author Automatika - JustInMind SL
 *
 */
public class FormBeanContainer extends ValidatorFormAndAction{
	/**
	 * The id of the formBean. Used to store information in the sesion
	 */
	protected String id;
	/**
	 * Contains the information recibed by the action which does is not classified (is not form the BO form bean neither the BoAdder).
	 */
	protected ValidatorFormAndAction nonBOData=new ValidatorFormAndAction();
	
	/**
	 * Creates a FormBeanContainer generating its id
	 */
	public FormBeanContainer(){
		id = (new Timestamp(System.nanoTime())).toString();
	}

	/**
	 * Returns the id of the formBeanContainer
	 * @return String with the id
	 */
	public String getId() {
		return id;
	}

	/**
	 * Set the id of the current FormBeanContainer
	 * @param id
	 */
	public void setId(String id) {
		this.id = id;
	}
	
	/**
	 * This function returns the code of the main FormBean (nested-pojo form bean) Contained in the container. this function should be overwritten if filled Containers.
	 * 
	 * @return string with the name of the object
	 */
	public String getMainFormBeanCode() {
		return null;
	}
	
	/**
	 * Return the NonObjectData nested formBean. It contains the information recibed by the action which does is not classified (is not form the nested-pojo-form-bean neither the BoAdder).
	 * @return the ValidatorFormAndAction
	 */
	public ValidatorFormAndAction getNonObjectData(){
		return nonBOData;
	}
	
	/**
	 * Set the NonObjectData nested formBean. It contains the information recibed by the action which does is not classified (is not form the nested-pojo-form-bean neither the BoAdder).
	 * @param nonBOData the ValidatorFormAndAction to set.
	 */
	public void setNonObjectData(ValidatorFormAndAction nonBOData){
		this.nonBOData=nonBOData;
	}
}
