/**
 * ====================================================================
 *
 * THIS FILE WAS GENERATED BY CC-RESOURCEFACTORY
 *
 * DO NOT MODIFY
 *
 * ====================================================================
 */

package com.cc.framework;

import java.util.Date;
import com.cc.framework.util.StringHelp;
import com.cc.framework.version.SystemType;
import com.cc.framework.version.VersionInfo;

/**
 * Program version
 *
 * @author		cc-resourcefactory
 */
public final class ComponentVersion implements VersionInfo {

	/**
	 * reference to singleton instance
	 */
	private static ComponentVersion instance = new ComponentVersion();

	/**
	 * System Type
	 */
	private SystemType systype = SystemType.SYSTYPE_PRODUCTION;

	/**
	 * constructor
	 */
	private ComponentVersion() {
		super();
	}

	/**
	 * returns the singleton instance
	 * @return		singleton instance
	 */
	public static ComponentVersion instance() {
		return instance;
	}

	/**
	 * @see com.cc.framework.version.VersionInfo#getProductBuildDate()
	 */
	public Date getProductBuildDate() {
		return new Date(1133209590313L);
	}

	/**
	 * @see com.cc.framework.version.VersionInfo#getProductBuildNumber()
	 */
	public String getProductBuildNumber() {
		return "021";
	}

	/**
	 * @see com.cc.framework.version.VersionInfo#getProductMajorVersion()
	 */
	public int getProductMajorVersion() {
		return 1;
	}

	/**
	 * @see com.cc.framework.version.VersionInfo#getProductMinorVersion()
	 */
	public int getProductMinorVersion() {
		return 6;
	}

	/**
	 * @see com.cc.framework.version.VersionInfo#getProductName()
	 */
	public String getProductName() {
		return "common-controls";
	}

	/**
	 * @see com.cc.framework.version.VersionInfo#getProductNameExtension()
	 */
	public String getProductNameExtension() {
		return "released";
	}

	/**
	 * @see com.cc.framework.version.VersionInfo#getProductVersion()
	 */
	public String getProductVersion() {
		return StringHelp.join(
			new String[] {
				String.valueOf(getProductMajorVersion()),
				String.valueOf(getProductMinorVersion()),
				getProductBuildNumber()},
			'.');
	}

	/**
	 * @see com.cc.framework.version.VersionInfo#getProductVendor()
	 */
	public String getProductVendor() {
		return "SCC Informationssysteme GmbH";
	}

	/**
	 * @see com.cc.framework.version.VersionInfo#getProductVendorSite()
	 */
	public String getProductVendorSite() {
		return "www.scc-gmbh.com";
	}

	/**
	 * @see com.cc.framework.version.VersionInfo#getSystemType()
	 */
	public SystemType getSystemType() {
		return systype;
	}
	/**
	 * Sets the system type
	 * @param	systype The system type to set
	 */
	public void setSystemType(SystemType systype) {
		this.systype = systype;
	}
}
