/**
 * $Header: d:/repository/cvs/cc-framework/source/com/cc/framework/FrameworkResources.java,v 1.75 2005/11/26 13:52:58 P001002 Exp $
 * $Revision: 1.75 $
 * $Date: 2005/11/26 13:52:58 $
 *
 * ====================================================================
 *
 * THIS FILE WAS GENERATED BY CC-RESOURCEFACTORY
 *
 * USER...........: P001002
 * BUILD-FACTORY..: v1.6.029
 * BUILD-DATE.....: Sat Nov 26 15:26:14 CET 2005
 * BUILD-DIRECTORY: C:\eclipse31\workspace\cc-framework
 * BUILD-FILE.....: C:\eclipse31\workspace\cc-framework\build\resources\bundle-fw.xml
 *
 * DO NOT MODIFY
 *
 * ====================================================================
 */

package com.cc.framework;

/**
 * Resource Keys for the FrameworkResources Resource Bundle
 *
 * @author		cc-resourcefactory
 */
public interface FrameworkResources {

	/** fw.calendar.ampm */
	public String FW_CALENDAR_AMPM = "fw.calendar.ampm";

	/** fw.calendar.button.cancel.label */
	public String FW_CALENDAR_BUTTON_CANCEL_LABEL = "fw.calendar.button.cancel.label";

	/** fw.calendar.button.cancel.tooltip */
	public String FW_CALENDAR_BUTTON_CANCEL_TOOLTIP = "fw.calendar.button.cancel.tooltip";

	/** fw.calendar.button.cancel.width */
	public String FW_CALENDAR_BUTTON_CANCEL_WIDTH = "fw.calendar.button.cancel.width";

	/** fw.calendar.button.ok.label */
	public String FW_CALENDAR_BUTTON_OK_LABEL = "fw.calendar.button.ok.label";

	/** fw.calendar.button.ok.tooltip */
	public String FW_CALENDAR_BUTTON_OK_TOOLTIP = "fw.calendar.button.ok.tooltip";

	/** fw.calendar.button.ok.width */
	public String FW_CALENDAR_BUTTON_OK_WIDTH = "fw.calendar.button.ok.width";

	/** fw.calendar.button.today.label */
	public String FW_CALENDAR_BUTTON_TODAY_LABEL = "fw.calendar.button.today.label";

	/** fw.calendar.image.nextmonth.alt */
	public String FW_CALENDAR_IMAGE_NEXTMONTH_ALT = "fw.calendar.image.nextmonth.alt";

	/** fw.calendar.image.nextmonth.tooltip */
	public String FW_CALENDAR_IMAGE_NEXTMONTH_TOOLTIP = "fw.calendar.image.nextmonth.tooltip";

	/** fw.calendar.image.nextyear.alt */
	public String FW_CALENDAR_IMAGE_NEXTYEAR_ALT = "fw.calendar.image.nextyear.alt";

	/** fw.calendar.image.nextyear.tooltip */
	public String FW_CALENDAR_IMAGE_NEXTYEAR_TOOLTIP = "fw.calendar.image.nextyear.tooltip";

	/** fw.calendar.image.prevmonth.alt */
	public String FW_CALENDAR_IMAGE_PREVMONTH_ALT = "fw.calendar.image.prevmonth.alt";

	/** fw.calendar.image.prevmonth.tooltip */
	public String FW_CALENDAR_IMAGE_PREVMONTH_TOOLTIP = "fw.calendar.image.prevmonth.tooltip";

	/** fw.calendar.image.prevyear.alt */
	public String FW_CALENDAR_IMAGE_PREVYEAR_ALT = "fw.calendar.image.prevyear.alt";

	/** fw.calendar.image.prevyear.tooltip */
	public String FW_CALENDAR_IMAGE_PREVYEAR_TOOLTIP = "fw.calendar.image.prevyear.tooltip";

	/** fw.calendar.months */
	public String FW_CALENDAR_MONTHS = "fw.calendar.months";

	/** fw.calendar.weekdays */
	public String FW_CALENDAR_WEEKDAYS = "fw.calendar.weekdays";

	/** fw.calendar.window.height */
	public String FW_CALENDAR_WINDOW_HEIGHT = "fw.calendar.window.height";

	/** fw.calendar.window.title */
	public String FW_CALENDAR_WINDOW_TITLE = "fw.calendar.window.title";

	/** fw.calendar.window.width */
	public String FW_CALENDAR_WINDOW_WIDTH = "fw.calendar.window.width";

	/** fw.colorpicker.window.title */
	public String FW_COLORPICKER_WINDOW_TITLE = "fw.colorpicker.window.title";

	/** fw.empty.gauge */
	public String FW_EMPTY_GAUGE = "fw.empty.gauge";

	/** fw.empty.text */
	public String FW_EMPTY_TEXT = "fw.empty.text";

	/** fw.form.required */
	public String FW_FORM_REQUIRED = "fw.form.required";

	/** fw.help.onclick */
	public String FW_HELP_ONCLICK = "fw.help.onclick";

	/** fw.help.target */
	public String FW_HELP_TARGET = "fw.help.target";

	/** fw.help.tooltip */
	public String FW_HELP_TOOLTIP = "fw.help.tooltip";

	/** fw.items */
	public String FW_ITEMS = "fw.items";

	/** fw.items.1te */
	public String FW_ITEMS_1TE = "fw.items.1te";

	/** fw.items.infinite */
	public String FW_ITEMS_INFINITE = "fw.items.infinite";

	/** fw.items.noentries */
	public String FW_ITEMS_NOENTRIES = "fw.items.noentries";

	/** fw.items.range */
	public String FW_ITEMS_RANGE = "fw.items.range";

	/** fw.page.1te */
	public String FW_PAGE_1TE = "fw.page.1te";

	/** fw.page.infinite */
	public String FW_PAGE_INFINITE = "fw.page.infinite";

	/** fw.page.noentries */
	public String FW_PAGE_NOENTRIES = "fw.page.noentries";

	/** fw.page.range */
	public String FW_PAGE_RANGE = "fw.page.range";

	/** fw.scheduler.appointment */
	public String FW_SCHEDULER_APPOINTMENT = "fw.scheduler.appointment";

	/** fw.scheduler.dateformat.datetime */
	public String FW_SCHEDULER_DATEFORMAT_DATETIME = "fw.scheduler.dateformat.datetime";

	/** fw.scheduler.dateformat.day */
	public String FW_SCHEDULER_DATEFORMAT_DAY = "fw.scheduler.dateformat.day";

	/** fw.scheduler.dateformat.detail */
	public String FW_SCHEDULER_DATEFORMAT_DETAIL = "fw.scheduler.dateformat.detail";

	/** fw.scheduler.dateformat.hour */
	public String FW_SCHEDULER_DATEFORMAT_HOUR = "fw.scheduler.dateformat.hour";

	/** fw.scheduler.dateformat.monthofyear */
	public String FW_SCHEDULER_DATEFORMAT_MONTHOFYEAR = "fw.scheduler.dateformat.monthofyear";

	/** fw.scheduler.dateformat.time */
	public String FW_SCHEDULER_DATEFORMAT_TIME = "fw.scheduler.dateformat.time";

	/** fw.scheduler.dateformat.week */
	public String FW_SCHEDULER_DATEFORMAT_WEEK = "fw.scheduler.dateformat.week";

	/** fw.scheduler.dateformat.weekday */
	public String FW_SCHEDULER_DATEFORMAT_WEEKDAY = "fw.scheduler.dateformat.weekday";

	/** fw.scheduler.dateformat.weekday.short */
	public String FW_SCHEDULER_DATEFORMAT_WEEKDAY_SHORT = "fw.scheduler.dateformat.weekday.short";

	/** fw.scheduler.pattern.daily.day */
	public String FW_SCHEDULER_PATTERN_DAILY_DAY = "fw.scheduler.pattern.daily.day";

	/** fw.scheduler.pattern.daily.weekday */
	public String FW_SCHEDULER_PATTERN_DAILY_WEEKDAY = "fw.scheduler.pattern.daily.weekday";

	/** fw.scheduler.pattern.daily.weekendday */
	public String FW_SCHEDULER_PATTERN_DAILY_WEEKENDDAY = "fw.scheduler.pattern.daily.weekendday";

	/** fw.scheduler.pattern.monthly */
	public String FW_SCHEDULER_PATTERN_MONTHLY = "fw.scheduler.pattern.monthly";

	/** fw.scheduler.pattern.monthly.nth */
	public String FW_SCHEDULER_PATTERN_MONTHLY_NTH = "fw.scheduler.pattern.monthly.nth";

	/** fw.scheduler.pattern.none */
	public String FW_SCHEDULER_PATTERN_NONE = "fw.scheduler.pattern.none";

	/** fw.scheduler.pattern.option.day */
	public String FW_SCHEDULER_PATTERN_OPTION_DAY = "fw.scheduler.pattern.option.day";

	/** fw.scheduler.pattern.option.first */
	public String FW_SCHEDULER_PATTERN_OPTION_FIRST = "fw.scheduler.pattern.option.first";

	/** fw.scheduler.pattern.option.fourth */
	public String FW_SCHEDULER_PATTERN_OPTION_FOURTH = "fw.scheduler.pattern.option.fourth";

	/** fw.scheduler.pattern.option.last */
	public String FW_SCHEDULER_PATTERN_OPTION_LAST = "fw.scheduler.pattern.option.last";

	/** fw.scheduler.pattern.option.second */
	public String FW_SCHEDULER_PATTERN_OPTION_SECOND = "fw.scheduler.pattern.option.second";

	/** fw.scheduler.pattern.option.third */
	public String FW_SCHEDULER_PATTERN_OPTION_THIRD = "fw.scheduler.pattern.option.third";

	/** fw.scheduler.pattern.option.weekday */
	public String FW_SCHEDULER_PATTERN_OPTION_WEEKDAY = "fw.scheduler.pattern.option.weekday";

	/** fw.scheduler.pattern.option.weekendday */
	public String FW_SCHEDULER_PATTERN_OPTION_WEEKENDDAY = "fw.scheduler.pattern.option.weekendday";

	/** fw.scheduler.pattern.weekly */
	public String FW_SCHEDULER_PATTERN_WEEKLY = "fw.scheduler.pattern.weekly";

	/** fw.scheduler.pattern.yearly */
	public String FW_SCHEDULER_PATTERN_YEARLY = "fw.scheduler.pattern.yearly";

	/** fw.scheduler.pattern.yearly.nth */
	public String FW_SCHEDULER_PATTERN_YEARLY_NTH = "fw.scheduler.pattern.yearly.nth";

	/** fw.scheduler.recurrencetype.daily */
	public String FW_SCHEDULER_RECURRENCETYPE_DAILY = "fw.scheduler.recurrencetype.daily";

	/** fw.scheduler.recurrencetype.monthly */
	public String FW_SCHEDULER_RECURRENCETYPE_MONTHLY = "fw.scheduler.recurrencetype.monthly";

	/** fw.scheduler.recurrencetype.none */
	public String FW_SCHEDULER_RECURRENCETYPE_NONE = "fw.scheduler.recurrencetype.none";

	/** fw.scheduler.recurrencetype.weekly */
	public String FW_SCHEDULER_RECURRENCETYPE_WEEKLY = "fw.scheduler.recurrencetype.weekly";

	/** fw.scheduler.recurrencetype.yearly */
	public String FW_SCHEDULER_RECURRENCETYPE_YEARLY = "fw.scheduler.recurrencetype.yearly";

	/** fw.swapselect.add */
	public String FW_SWAPSELECT_ADD = "fw.swapselect.add";

	/** fw.swapselect.add.all */
	public String FW_SWAPSELECT_ADD_ALL = "fw.swapselect.add.all";

	/** fw.swapselect.remove */
	public String FW_SWAPSELECT_REMOVE = "fw.swapselect.remove";

	/** fw.swapselect.remove.all */
	public String FW_SWAPSELECT_REMOVE_ALL = "fw.swapselect.remove.all";

	/** fw.tabbar.range */
	public String FW_TABBAR_RANGE = "fw.tabbar.range";

	/** fw.tabset.range */
	public String FW_TABSET_RANGE = "fw.tabset.range";

	/** fw.textarea.maxlength.message */
	public String FW_TEXTAREA_MAXLENGTH_MESSAGE = "fw.textarea.maxlength.message";

	/** fw.textpopup.button.icon.alt */
	public String FW_TEXTPOPUP_BUTTON_ICON_ALT = "fw.textpopup.button.icon.alt";

	/** fw.textpopup.button.icon.tooltip */
	public String FW_TEXTPOPUP_BUTTON_ICON_TOOLTIP = "fw.textpopup.button.icon.tooltip";

	/** fw.tooltip.checkall */
	public String FW_TOOLTIP_CHECKALL = "fw.tooltip.checkall";

	/** fw.tooltip.close */
	public String FW_TOOLTIP_CLOSE = "fw.tooltip.close";

	/** fw.tooltip.create.appointment */
	public String FW_TOOLTIP_CREATE_APPOINTMENT = "fw.tooltip.create.appointment";

	/** fw.tooltip.create.item */
	public String FW_TOOLTIP_CREATE_ITEM = "fw.tooltip.create.item";

	/** fw.tooltip.export.list */
	public String FW_TOOLTIP_EXPORT_LIST = "fw.tooltip.export.list";

	/** fw.tooltip.firstpage */
	public String FW_TOOLTIP_FIRSTPAGE = "fw.tooltip.firstpage";

	/** fw.tooltip.lastpage */
	public String FW_TOOLTIP_LASTPAGE = "fw.tooltip.lastpage";

	/** fw.tooltip.maximize */
	public String FW_TOOLTIP_MAXIMIZE = "fw.tooltip.maximize";

	/** fw.tooltip.minimize */
	public String FW_TOOLTIP_MINIMIZE = "fw.tooltip.minimize";

	/** fw.tooltip.nextpage */
	public String FW_TOOLTIP_NEXTPAGE = "fw.tooltip.nextpage";

	/** fw.tooltip.page */
	public String FW_TOOLTIP_PAGE = "fw.tooltip.page";

	/** fw.tooltip.prevpage */
	public String FW_TOOLTIP_PREVPAGE = "fw.tooltip.prevpage";

	/** fw.tooltip.print.list */
	public String FW_TOOLTIP_PRINT_LIST = "fw.tooltip.print.list";

	/** fw.tooltip.refresh.list */
	public String FW_TOOLTIP_REFRESH_LIST = "fw.tooltip.refresh.list";

	/** fw.tooltip.refresh.scheduler */
	public String FW_TOOLTIP_REFRESH_SCHEDULER = "fw.tooltip.refresh.scheduler";

	/** fw.tooltip.restore */
	public String FW_TOOLTIP_RESTORE = "fw.tooltip.restore";

	/** fw.tooltip.scheduler.addappointment */
	public String FW_TOOLTIP_SCHEDULER_ADDAPPOINTMENT = "fw.tooltip.scheduler.addappointment";

	/** fw.tooltip.scheduler.dayview */
	public String FW_TOOLTIP_SCHEDULER_DAYVIEW = "fw.tooltip.scheduler.dayview";

	/** fw.tooltip.scheduler.monthview */
	public String FW_TOOLTIP_SCHEDULER_MONTHVIEW = "fw.tooltip.scheduler.monthview";

	/** fw.tooltip.scheduler.more */
	public String FW_TOOLTIP_SCHEDULER_MORE = "fw.tooltip.scheduler.more";

	/** fw.tooltip.scheduler.nextdate */
	public String FW_TOOLTIP_SCHEDULER_NEXTDATE = "fw.tooltip.scheduler.nextdate";

	/** fw.tooltip.scheduler.prevdate */
	public String FW_TOOLTIP_SCHEDULER_PREVDATE = "fw.tooltip.scheduler.prevdate";

	/** fw.tooltip.scheduler.range */
	public String FW_TOOLTIP_SCHEDULER_RANGE = "fw.tooltip.scheduler.range";

	/** fw.tooltip.scheduler.weekview */
	public String FW_TOOLTIP_SCHEDULER_WEEKVIEW = "fw.tooltip.scheduler.weekview";

	/** fw.tooltip.scheduler.workweekview */
	public String FW_TOOLTIP_SCHEDULER_WORKWEEKVIEW = "fw.tooltip.scheduler.workweekview";

	/** fw.tooltip.scheduler.yearview */
	public String FW_TOOLTIP_SCHEDULER_YEARVIEW = "fw.tooltip.scheduler.yearview";

	/** fw.tooltip.uncheckall */
	public String FW_TOOLTIP_UNCHECKALL = "fw.tooltip.uncheckall";

}
